export const IOS_PLATFORM = 'iOS'
export const ANDROID_PLATFORM = 'Android'

export const ACCESS_TOKEN_KEY = 'access_token'
export const REFRESH_TOKEN_KEY = 'refresh_token'
export const CURRENT_USER_INFO_KEY = 'currentUserInfo'
export const IS_SUBSCRIBED_KEY = 'SubscribedInServer'
export const JPUSH_TOKEN_KEY = 'JpushDeviceKey'
export const APNS_NEW_TOKEN_KEY = 'apnsNewToken'
export const APNS_OLD_TOKEN_KEY = 'apnsOldToken'
export const LANGUAGE_KEY = 'language'
export const LANGUAGE_ENGLISH = 'en'
export const LANGUAGE_CHINESE = 'cn'
